language: objective-c

before_install:
  - gem install cocoapods
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
  
notifications:
  webhooks: 
    - http://staging.ironbroker.flatironschool.com/e/travis/build
    - http://5e5a4ba.ngrok.com/e/travis/build

script: xctool -reporter json-stream -workspace locationTrivia-tableviews.xcworkspace -sdk iphonesimulator -destination "name=iPhone Retina (4-inch)" -scheme locationTrivia-tableviews build test
