language: objective-c

before_install:
  - gem install cocoapods
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

notifications:
  webhooks:
    - http://progress.flatironschool.com/submissions
    - http://5e5a4ba.ngrok.com/e/travis/build
    - http://requestb.in/x1g25bx1
script: xctool -reporter json-stream -workspace locationTrivia-tableviews.xcworkspace -sdk iphonesimulator -destination "name=iPhone Retina (4-inch)" -scheme locationTrivia-tableviews build test
