language: objective-c

before_install:
  - gem install cocoapods
  - brew update
  - brew upgrade xctool
  
notifications:
  webhooks: 
    - http://progress.flatironschool.com/submissions
    - http://staging.ironbroker.flatironschool.com/e/travis/build

script: xctool -reporter json-stream -workspace locationTrivia-tableviews.xcworkspace -sdk iphonesimulator -destination "name=iPhone Retina (4-inch)" -scheme locationTrivia-tableviews build test
